# Generated by Django 6.1.1 on 2026-10-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjaman',
            name='buku_fisik',
        ),
        migrations.AddField(
            model_name='bukudigital',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bukudigital',
            name='format_file',
            field=models.CharField(default='PDF', max_length=10),
        ),
        migrations.AddField(
            model_name='jurnal',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='max_loans',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='status',
            field=models.CharField(default='Dibaca', max_length=20),
        ),
        migrations.DeleteModel(
            name='BukuFisik',
        ),
    ]
