# Generated by Django 6.1.1 on 2026-10-02 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_remove_peminjaman_buku_fisik_bukudigital_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_disimpan', models.DateTimeField(auto_now_add=True)),
                ('buku_digital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.bukudigital')),
                ('jurnal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.jurnal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
