# Generated by Django 6.1.1 on 2026-10-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='tanggal_kembali',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
