# Generated by Django 6.1.1 on 2026-10-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_peminjaman_tanggal_kembali'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profil/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nama_tampilan',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
