# Generated by Django 6.1.1 on 2026-10-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0005_customuser_foto_background_customuser_foto_profil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukudigital',
            name='deskripsi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bukudigital',
            name='ia_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bukudigital',
            name='tahun_terbit',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='jurnal',
            name='tahun_terbit',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
